server:
  port: 8082

spring:
#  batch:
#    initialize-schema: ALWAYS
#    job:
#      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch_meta
    username: batch_admin
    password: batch_admin
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true