spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch_meta
    username: batch_admin
    password: batch_admin
  batch :
    job:  
      enabled : false
    initialize-schema: ALWAYS
  quartz:
    jdbc:
      initialize-schema: ALWAYS

org:
  quartz:
    scheduler:
      instanceId: AUTO
      instanceName: kingbbode-example
      makeSchedulerThreadDaemon : true
      interruptJobsOnShutdown  : true
    jobStore:
      clusterCheckinInterval: 20000
      driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      isClustered: true
      misfireThreshold: 60000
      tablePrefix: QRTZ_
      useProperties: false
    threadPool:
      threadCount: 5
      makeThreadsDaemons : true